# Generated by Django 5.2.4 on 2025-07-05 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('description', models.TextField(blank=True, help_text='Optional: A detailed description of the event.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this to hide the event from public view.')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='core.event')),
            ],
            options={
                'verbose_name': 'Attendee',
                'verbose_name_plural': 'Attendees',
                'ordering': ['-registration_date'],
                'unique_together': {('user', 'event')},
            },
        ),
        migrations.CreateModel(
            name='EventQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='The question text that the user will see.', max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text (Single Line)'), ('textarea', 'Text (Multi-Line)'), ('dropdown', 'Dropdown'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkboxes (Multiple Answers)')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('choices', models.TextField(blank=True, help_text='For Dropdown, Radio, or Checkbox fields. Enter one choice per line.')),
                ('order', models.PositiveIntegerField(default=0, help_text='The order in which the question will appear on the form.')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.event')),
            ],
            options={
                'verbose_name': 'Event Question',
                'verbose_name_plural': 'Event Questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AttendeeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.attendee')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.eventquestion')),
            ],
            options={
                'verbose_name': 'Attendee Answer',
                'verbose_name_plural': 'Attendee Answers',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
