# Generated by Django 5.2.4 on 2025-07-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_profile',
            field=models.URLField(blank=True, help_text='e.g., https://linkedin.com/in/yourname', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='professional_interests',
            field=models.CharField(blank=True, help_text='Comma-separated interests, e.g., AI, Marketing, Fintech', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, help_text='Your personal or company website.', max_length=255),
        ),
    ]
