# Generated by Django 5.2.4 on 2025-07-06 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_linkedin_profile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='A featured image for the event, displayed on home/list pages.', null=True, upload_to='event_images/'),
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The speaker's full name.", max_length=200)),
                ('bio', models.TextField(help_text='A short biography of the speaker.')),
                ('picture', models.ImageField(blank=True, help_text='A headshot or profile picture for the speaker.', null=True, upload_to='speakers/')),
                ('user', models.ForeignKey(blank=True, help_text='(Optional) Link this speaker to a registered user account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Speaker',
                'verbose_name_plural': 'Speakers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A user-friendly title for the resource.', max_length=200)),
                ('file', models.FileField(help_text='The uploaded file (PDF, PPT, image, etc.).', upload_to='event_resources/')),
                ('is_visible', models.BooleanField(default=False, help_text='Check this box to make the resource visible to public attendees.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.event')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='The user account that performed the upload.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.speaker')),
            ],
            options={
                'verbose_name': 'Event Resource',
                'verbose_name_plural': 'Event Resources',
                'ordering': ['event', 'speaker', 'title'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(blank=True, help_text='Select speakers for this event.', related_name='events', to='core.speaker'),
        ),
    ]
