# Generated by Django 5.2.4 on 2025-07-06 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_featured_image_speaker_eventresource_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_datetime'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 6, 11, 58, 2, 146965, tzinfo=datetime.timezone.utc), help_text='The date the event was created in the system.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='The date and time the event ends.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 6, 11, 59, 26, 419708, tzinfo=datetime.timezone.utc), help_text='The date and time the event starts.'),
            preserve_default=False,
        ),
    ]
