# Generated by Django 5.2.4 on 2025-07-06 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event_event_type_event_online_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.event')),
                ('speakers', models.ManyToManyField(blank=True, help_text='Speakers for this specific session.', related_name='sessions', to='core.speaker')),
            ],
            options={
                'verbose_name': 'Event Session',
                'verbose_name_plural': 'Event Sessions',
                'ordering': ['start_time'],
            },
        ),
    ]
